import { useEffect, useState } from 'react'
import { loadEditorConfig, submitEditorExport, type EditorConfig } from './client-dashboard-service'
import { supabase } from '../lib/supabase'

type Draft = Record<string, { text: string; size: string; color: string; logo: string }>
const keyFor = (projectId: string, versionId: string) => `no_editor:${projectId}:${versionId}`
const download = (name: string, text: string) => { const url = URL.createObjectURL(new Blob([text], { type: 'text/plain' })); const a = document.createElement('a'); a.href = url; a.download = name; a.click(); URL.revokeObjectURL(url) }

export function EditorModule({ projectId }: { projectId: string }) {
  const [config, setConfig] = useState<EditorConfig | null>(null); const [draft, setDraft] = useState<Draft>({}); const [message, setMessage] = useState('')
  useEffect(() => { void loadEditorConfig(projectId).then((next) => { setConfig(next); if (next) setDraft(JSON.parse(localStorage.getItem(keyFor(projectId, next.versionId)) || '{}')) }).catch(() => setMessage('Não foi possível carregar o Editor.')) }, [projectId])
  if (!config) return <section className="rounded-2xl border border-borda bg-white p-6"><h2 className="text-xl font-bold">Editor</h2><p className="mt-2 text-cinza">Nenhuma configuração de edição foi liberada para a versão atual.</p></section>
  const change = (id: string, field: string, value: string) => setDraft((old) => ({ ...old, [id]: Object.assign({ text: '', size: '16', color: '#111111', logo: '' }, old[id], { [field]: value }) }))
  const save = () => { localStorage.setItem(keyFor(projectId, config.versionId), JSON.stringify(draft)); setMessage('Ajustes salvos neste navegador.') }
  const send = async () => { const changes = Object.entries(draft).map(([component, value]) => ({ component, before: {}, after: value })); const requestId = crypto.randomUUID(); const files = { 'editor.md': `# Ajustes ${config.label}\n${JSON.stringify(changes, null, 2)}`, 'editor.cfg': JSON.stringify(draft, null, 2), 'editor.css': Object.entries(draft).map(([id, v]) => `[data-editor="${id}"]{font-size:${v.size}px;color:${v.color}}`).join('\n') }; const manifest = { project_id: projectId, base_version_label: config.label, changes, files: Object.keys(files).map((name) => `${projectId}/${requestId}/${name}`) }; for (const [name, text] of Object.entries(files)) { const { error } = await supabase.storage.from('editor-exports').upload(`${projectId}/${requestId}/${name}`, new Blob([text], { type: 'text/plain' }), { upsert: false }); if (error) throw error; download(name, text) } download('manifest.json', JSON.stringify(manifest, null, 2)); await submitEditorExport(projectId, config.versionId, changes, manifest, requestId); setMessage('Pacote privado enviado para análise. A Nó implementa na próxima versão.') }
  return <section className="rounded-2xl border border-borda bg-white p-6"><h2 className="text-xl font-bold">Editor · {config.label}</h2><p className="mt-2 text-cinza">Experimente os ajustes, exporte suas preferências e a Nó implementa na próxima versão.</p><div className="mt-5 space-y-4">{config.allowedComponents.map((component) => <fieldset className="rounded-xl bg-osso p-4" key={component.id}><legend className="font-semibold">{component.label ?? component.id}</legend><input aria-label={`Texto ${component.id}`} className="mt-2 w-full rounded border p-2" value={draft[component.id]?.text ?? ''} onChange={(e) => change(component.id, 'text', e.target.value)} placeholder="Texto" /><div className="mt-2 flex gap-2"><input aria-label={`Tamanho ${component.id}`} type="number" className="w-24 rounded border p-2" value={draft[component.id]?.size ?? '16'} onChange={(e) => change(component.id, 'size', e.target.value)} /><input aria-label={`Cor ${component.id}`} type="color" value={draft[component.id]?.color ?? '#111111'} onChange={(e) => change(component.id, 'color', e.target.value)} /><input aria-label={`Logo ${component.id}`} className="flex-1 rounded border p-2" value={draft[component.id]?.logo ?? ''} onChange={(e) => change(component.id, 'logo', e.target.value)} placeholder="URL do logo" /></div></fieldset>)}</div><div className="mt-5 flex gap-3"><button type="button" className="rounded-xl border px-4 py-2" onClick={save}>Salvar ajustes</button><button type="button" className="rounded-xl bg-tinta px-4 py-2 text-white" onClick={() => void send()}>Enviar para análise</button></div>{message && <p role="status" className="mt-3 text-sm">{message}</p>}</section>
}
