import { useCallback, useEffect, useReducer, useRef, useState } from 'react'
import {
  finalizeEditorExport,
  loadEditorConfig,
  submitEditorExport,
  uploadEditorExportFiles,
  uploadEditorImage,
  EDITOR_IMAGE_MAX_BYTES,
  EDITOR_IMAGE_TYPES,
  type EditorConfig,
} from './client-dashboard-service'

type DraftValue = {
  text: string
  size: string
  color: string
  logo: string
  x: string
  y: string
  width: string
  height: string
}
type Draft = Record<string, Partial<DraftValue>>
type Component = EditorConfig['allowedComponents'][number]
// What the preview told us about an element: how to name it in the Nó
// dashboard and what it looked like before the client touched it.
type ComponentMeta = {
  label?: string
  screen?: string
  controls?: string[]
  before?: Partial<DraftValue>
}
type Meta = Record<string, ComponentMeta>
const contentControls = ['text', 'size', 'color', 'logo'] as const
const layoutControls = ['x', 'y', 'width', 'height'] as const
const allFields = [...contentControls, ...layoutControls] as const
// Matches ids generated by the preview bridge in automatic mode ("*" in the allowlist).
const AUTO_ID = /^auto:[A-Za-z0-9#/._-]{1,300}$/
const emptyValue: DraftValue = {
  text: '',
  size: '16',
  color: '#111111',
  logo: '',
  x: '0',
  y: '0',
  width: '',
  height: '',
}
// Undo history: one entry per deliberate change. A drag or a burst of typing
// on the same element and control collapses into a single step.
const HISTORY_LIMIT = 50
const COALESCE_MS = 800
type EditorState = { draft: Draft; history: Draft[]; lastKey: string; lastAt: number }
type EditorAction =
  | { type: 'change'; id: string; field: keyof DraftValue; value: string; at: number }
  | { type: 'undo' }
  | { type: 'reset'; draft: Draft }
const initialEditorState: EditorState = { draft: {}, history: [], lastKey: '', lastAt: 0 }

function editorReducer(state: EditorState, action: EditorAction): EditorState {
  if (action.type === 'reset') return { ...initialEditorState, draft: action.draft }
  if (action.type === 'undo') {
    const previous = state.history.at(-1)
    return previous
      ? { draft: previous, history: state.history.slice(0, -1), lastKey: '', lastAt: 0 }
      : state
  }
  if (state.draft[action.id]?.[action.field] === action.value) return state
  const group = (layoutControls as readonly string[]).includes(action.field) ? 'layout' : action.field
  const key = `${action.id}:${group}`
  const coalesce = key === state.lastKey && action.at - state.lastAt < COALESCE_MS
  return {
    draft: { ...state.draft, [action.id]: { ...state.draft[action.id], [action.field]: action.value } },
    history: coalesce ? state.history : [...state.history, state.draft].slice(-HISTORY_LIMIT),
    lastKey: key,
    lastAt: action.at,
  }
}

// "V1" → "vira a versão 2": the promise shown on the sent stamp.
function nextVersionText(label: string) {
  const match = /(\d+)/.exec(label)
  return match ? `vira a versão ${Number(match[1]) + 1}` : 'entra na próxima versão'
}

function editableTarget(target: EventTarget | null) {
  return target instanceof HTMLElement && (target.isContentEditable || /^(INPUT|TEXTAREA|SELECT)$/.test(target.tagName))
}

const keyFor = (projectId: string, versionId: string) =>
  `no_editor:${projectId}:${versionId}`
const metaKeyFor = (projectId: string, versionId: string) =>
  `no_editor_meta:${projectId}:${versionId}`

function controlsFor(component: Component) {
  return [...new Set([...(component.controls ?? contentControls), ...layoutControls])]
}

function componentFor(config: EditorConfig, meta: Meta, id: string): Component | null {
  if (id === '*') return null
  const configured = config.allowedComponents.find((item) => item.id === id)
  if (configured) return configured
  const wildcard = config.allowedComponents.find((item) => item.id === '*')
  if (!wildcard || !AUTO_ID.test(id)) return null
  const allowedControls: readonly string[] = wildcard.controls ?? contentControls
  const info = meta[id]
  return {
    id,
    label: info?.label ?? 'Elemento da página',
    screen: info?.screen ?? 'Página',
    controls: (info?.controls ?? allowedControls).filter((control) =>
      allowedControls.includes(control),
    ),
  }
}

function boundedText(value: unknown, size: number) {
  return typeof value === 'string' && value.trim()
    ? value.trim().slice(0, size)
    : undefined
}

function sanitizeMeta(value: unknown): ComponentMeta | null {
  if (!value || typeof value !== 'object' || Array.isArray(value)) return null
  const fields = value as Record<string, unknown>
  const result: ComponentMeta = {}
  const label = boundedText(fields.label, 120)
  const screen = boundedText(fields.screen, 80)
  if (label) result.label = label
  if (screen) result.screen = screen
  if (Array.isArray(fields.controls))
    result.controls = fields.controls.filter(
      (control): control is string =>
        typeof control === 'string' &&
        (contentControls as readonly string[]).includes(control),
    )
  if (fields.before && typeof fields.before === 'object' && !Array.isArray(fields.before)) {
    const before: Partial<DraftValue> = {}
    for (const field of allFields) {
      const candidate = (fields.before as Record<string, unknown>)[field]
      if (typeof candidate === 'string') before[field] = candidate.slice(0, 2000)
    }
    result.before = before
  }
  return result
}

function readMeta(projectId: string, config: EditorConfig): Meta {
  try {
    const value: unknown = JSON.parse(
      localStorage.getItem(metaKeyFor(projectId, config.versionId)) ?? '{}',
    )
    if (!value || typeof value !== 'object' || Array.isArray(value)) return {}
    const result: Meta = {}
    for (const [id, entry] of Object.entries(value)) {
      const clean = sanitizeMeta(entry)
      if (clean && (AUTO_ID.test(id) || config.allowedComponents.some((item) => item.id === id)))
        result[id] = clean
    }
    return result
  } catch {
    return {}
  }
}

// `auto:#valores/div.1/h2.1` → `#valores > div:nth-of-type(1) > h2:nth-of-type(1)`
function cssSelectorFor(id: string) {
  if (!AUTO_ID.test(id)) return `[data-editor="${id}"]`
  // Photos are addressed by their original file: `auto:src/quem/thais-3.jpg`.
  if (id.startsWith('auto:src/')) return `img[src$="${id.split('/').pop()}"]`
  const parts = id.slice('auto:'.length).split('/')
  const root = parts[0]?.startsWith('#') ? (parts.shift() ?? 'body') : 'body'
  return [
    root,
    ...parts.map((part) => {
      const [tag, index] = part.split('.')
      return `${tag}:nth-of-type(${index})`
    }),
  ].join(' > ')
}

function validLayoutValue(field: string, value: string) {
  if (value === '' && (field === 'width' || field === 'height')) return true
  if (!/^-?\d+(\.\d+)?$/.test(value)) return false
  const numeric = Number(value)
  if (field === 'x' || field === 'y') return numeric >= -2000 && numeric <= 2000
  return numeric >= 20 && numeric <= 4000
}

function readDraft(projectId: string, config: EditorConfig, meta: Meta): Draft {
  try {
    const value: unknown = JSON.parse(
      localStorage.getItem(keyFor(projectId, config.versionId)) ?? '{}',
    )
    if (!value || typeof value !== 'object' || Array.isArray(value)) return {}
    const result: Draft = {}
    for (const [id, candidate] of Object.entries(value)) {
      const component = componentFor(config, meta, id)
      if (!component) continue
      if (
        !candidate ||
        typeof candidate !== 'object' ||
        Array.isArray(candidate)
      )
        continue
      const fields = candidate as Record<string, unknown>
      const legacyFullDraft = allFields.every(
        (field) => typeof fields[field] === 'string',
      )
      const nextValue: Partial<DraftValue> = {}
      for (const field of allFields) {
        if (
          controlsFor(component).includes(field) &&
          typeof fields[field] === 'string' &&
          (!legacyFullDraft || fields[field] !== emptyValue[field])
        )
          nextValue[field] = fields[field]
      }
      if (
        nextValue.color !== undefined &&
        !/^#[0-9a-f]{6}$/i.test(nextValue.color)
      )
        delete nextValue.color
      if (
        nextValue.size !== undefined &&
        (!Number.isFinite(Number(nextValue.size)) ||
          Number(nextValue.size) < 8 ||
          Number(nextValue.size) > 160)
      )
        delete nextValue.size
      for (const field of layoutControls) {
        const fieldValue = nextValue[field]
        if (fieldValue !== undefined && !validLayoutValue(field, fieldValue))
          delete nextValue[field]
      }
      if (Object.keys(nextValue).length) result[component.id] = nextValue
    }
    return result
  } catch {
    return {}
  }
}

function previewUrl(config: EditorConfig | null) {
  if (!config?.bridgeEnabled) return null
  try {
    const url = new URL(config.buildReference)
    if (url.protocol !== 'https:' && url.protocol !== 'http:') return null
    if (
      window.location.hostname === 'localhost' &&
      url.pathname.startsWith('/prototipos/')
    ) {
      const localPath = url.pathname.endsWith('/')
        ? `${url.pathname}index.html`
        : url.pathname
      return new URL(`${localPath}${url.search}${url.hash}`, window.location.origin)
    }
    return url
  } catch {
    return null
  }
}

export function EditorModule({ projectId }: { projectId: string }) {
  const [previewRevision, setPreviewRevision] = useState(0)
  const [selectedComponent, setSelectedComponent] = useState('')
  const [device, setDevice] = useState<'desktop' | 'mobile'>('desktop')
  const [editorMode, setEditorMode] = useState(false)
  const [config, setConfig] = useState<EditorConfig | null>(null)
  const [{ draft, history }, dispatch] = useReducer(editorReducer, initialEditorState)
  const [meta, setMeta] = useState<Meta>({})
  const [previewValues, setPreviewValues] = useState<Draft>({})
  const [loading, setLoading] = useState(true)
  const [loadFailed, setLoadFailed] = useState(false)
  const [sending, setSending] = useState(false)
  // The draft exactly as it was sent; any later change brings the button back.
  const [sentDraft, setSentDraft] = useState<string | null>(null)
  const [stampDismissed, setStampDismissed] = useState(false)
  const [uploading, setUploading] = useState(false)
  const [imageError, setImageError] = useState<{ id: string; text: string } | null>(null)
  const [confirmDiscard, setConfirmDiscard] = useState(false)
  const [message, setMessage] = useState('')
  const frameRef = useRef<HTMLIFrameElement>(null)

  const change = useCallback(
    (id: string, field: keyof DraftValue, value: string) => {
      setConfirmDiscard(false)
      dispatch({ type: 'change', id, field, value, at: Date.now() })
    },
    [],
  )
  const undo = useCallback(() => {
    setConfirmDiscard(false)
    dispatch({ type: 'undo' })
    setMessage('Última alteração desfeita.')
  }, [])

  const load = useCallback(() => {
    setLoading(true)
    setLoadFailed(false)
    void loadEditorConfig(projectId)
      .then((next) => {
        const nextMeta = next ? readMeta(projectId, next) : {}
        setConfig(next)
        setMeta(nextMeta)
        dispatch({ type: 'reset', draft: next ? readDraft(projectId, next, nextMeta) : {} })
      })
      .catch(() => setLoadFailed(true))
      .finally(() => setLoading(false))
  }, [projectId])
  useEffect(() => {
    let active = true
    void loadEditorConfig(projectId)
      .then((next) => {
        if (!active) return
        const nextMeta = next ? readMeta(projectId, next) : {}
        setConfig(next)
        setMeta(nextMeta)
        dispatch({ type: 'reset', draft: next ? readDraft(projectId, next, nextMeta) : {} })
      })
      .catch(() => {
        if (active) setLoadFailed(true)
      })
      .finally(() => {
        if (active) setLoading(false)
      })
    return () => {
      active = false
    }
  }, [projectId])

  useEffect(() => {
    // Fields keep the browser's own undo; elsewhere Ctrl/Cmd+Z undoes the editor.
    const onKeyDown = (event: KeyboardEvent) => {
      if (event.shiftKey || event.altKey || !(event.ctrlKey || event.metaKey)) return
      if (event.key.toLowerCase() !== 'z' || editableTarget(event.target) || !history.length) return
      event.preventDefault()
      undo()
    }
    window.addEventListener('keydown', onKeyDown)
    return () => window.removeEventListener('keydown', onKeyDown)
  }, [history.length, undo])

  const sendPreview = useCallback(() => {
    const target = previewUrl(config)
    if (!target || !config || !frameRef.current?.contentWindow) return
    frameRef.current.contentWindow.postMessage(
      {
        source: 'no-editor',
        type: 'NO_EDITOR_PREVIEW',
        version: 1,
        projectId,
        baseVersionId: config.versionId,
        changes: draft,
        selectedComponent,
        editorMode,
      },
      target.origin,
    )
  }, [config, draft, editorMode, projectId, selectedComponent])
  useEffect(() => sendPreview(), [sendPreview])

  useEffect(() => {
    const receivePreview = (event: MessageEvent) => {
      const target = previewUrl(config)
      const payload: unknown = event.data
      if (
        !editorMode ||
        !target ||
        !config ||
        event.origin !== target.origin ||
        event.source !== frameRef.current?.contentWindow ||
        !payload ||
        typeof payload !== 'object'
      )
        return
      const message = payload as Record<string, unknown>
      if (
        message.source !== 'no-editor-preview' ||
        message.version !== 1 ||
        message.projectId !== projectId ||
        message.baseVersionId !== config.versionId
      )
        return
      if (message.type === 'NO_EDITOR_UNDO') {
        if (history.length) undo()
        return
      }
      if (typeof message.componentId !== 'string') return
      const componentId = message.componentId
      const reported = sanitizeMeta({
        ...(message.meta && typeof message.meta === 'object' ? message.meta : {}),
        before: message.original,
      })
      // The bridge names elements from their untouched text, so its latest
      // label is authoritative; the first "before" seen is kept.
      const known = meta[componentId]
      const merged: ComponentMeta = { ...known, ...reported }
      if (known?.before || reported?.before)
        merged.before = { ...reported?.before, ...known?.before }
      const component = componentFor(config, { ...meta, [componentId]: merged }, componentId)
      if (!component) return
      if (JSON.stringify(known ?? null) !== JSON.stringify(merged))
        setMeta((current) => ({ ...current, [componentId]: merged }))
      setSelectedComponent(component.id)
      if (
        message.values &&
        typeof message.values === 'object' &&
        !Array.isArray(message.values)
      ) {
        const nextValue: Partial<DraftValue> = {}
        for (const [field, next] of Object.entries(message.values)) {
          if (
            (controlsFor(component) as readonly string[]).includes(field) &&
            typeof next === 'string' &&
            (!layoutControls.includes(field as (typeof layoutControls)[number]) ||
              validLayoutValue(field, next))
          )
            nextValue[field as keyof DraftValue] = next
        }
        setPreviewValues((current) => ({
          ...current,
          [component.id]: nextValue,
        }))
      }
      if (message.type !== 'NO_EDITOR_CHANGE') return
      if (
        !message.changes ||
        typeof message.changes !== 'object' ||
        Array.isArray(message.changes)
      )
        return
      const allowedControls = controlsFor(component)
      for (const [field, nextValue] of Object.entries(message.changes)) {
        if (
          !allowedControls.includes(field) ||
          typeof nextValue !== 'string' ||
          (layoutControls.includes(field as (typeof layoutControls)[number]) &&
            !validLayoutValue(field, nextValue))
        )
          continue
        change(component.id, field as keyof DraftValue, nextValue)
      }
    }
    window.addEventListener('message', receivePreview)
    return () => window.removeEventListener('message', receivePreview)
  }, [change, config, editorMode, history.length, meta, projectId, undo])

  if (loading)
    return (
      <section
        className="rounded-2xl border border-borda bg-white p-6"
        role="status"
      >
        Carregando Editor…
      </section>
    )
  if (loadFailed)
    return (
      <section className="rounded-2xl border border-vermelho bg-vermelho-tint p-6">
        <h2 className="text-xl font-bold">Editor indisponível</h2>
        <button
          type="button"
          className="mt-4 rounded-xl bg-tinta px-4 py-2 text-white"
          onClick={load}
        >
          Tentar de novo
        </button>
      </section>
    )
  if (!config)
    return (
      <section className="rounded-2xl border border-borda bg-white p-6">
        <h2 className="text-xl font-bold">Editor</h2>
        <p className="mt-2 text-cinza">
          Nenhuma configuração de edição foi liberada para a versão atual.
        </p>
      </section>
    )

  const target = previewUrl(config)
  const persist = () => {
    localStorage.setItem(keyFor(projectId, config.versionId), JSON.stringify(draft))
    localStorage.setItem(metaKeyFor(projectId, config.versionId), JSON.stringify(meta))
  }
  const save = () => {
    try {
      persist()
      setMessage('Ajustes salvos neste navegador.')
    } catch {
      setMessage(
        'Não foi possível salvar neste navegador. Seus ajustes continuam abertos.',
      )
    }
  }
  const discard = () => {
    localStorage.removeItem(keyFor(projectId, config.versionId))
    localStorage.removeItem(metaKeyFor(projectId, config.versionId))
    dispatch({ type: 'reset', draft: {} })
    setMeta({})
    setPreviewRevision((revision) => revision + 1)
    setConfirmDiscard(false)
    setMessage('Rascunho descartado.')
  }
  const send = async () => {
    const changes = Object.entries(draft).flatMap(([id, value]) => {
      const allowed = componentFor(config, meta, id)
      if (!allowed) return []
      const fields: readonly string[] = controlsFor(allowed)
      const after = Object.fromEntries(
        Object.entries(value).filter(
          ([field, fieldValue]) => fields.includes(field) && typeof fieldValue === 'string',
        ),
      )
      const original: Partial<Record<string, string>> = meta[id]?.before ?? {}
      const before = Object.fromEntries(
        Object.keys(after).flatMap((field) =>
          typeof original[field] === 'string' ? [[field, original[field]]] : [],
        ),
      )
      return Object.keys(after).length
        ? [{
            screen: allowed.screen ?? 'geral',
            component: id,
            label: allowed.label ?? id,
            before,
            after,
          }]
        : []
    })
    if (changes.length === 0) {
      setMessage('Faça ao menos um ajuste antes de enviar.')
      return
    }
    setSending(true)
    setMessage('')
    try {
      persist()
      const coreFiles = {
        'editor.md': [
          `# Ajustes ${config.label}`,
          ...changes.map((item) =>
            [
              `## ${item.screen} / ${item.label}`,
              `Componente: \`${item.component}\` · seletor \`${cssSelectorFor(item.component)}\``,
              ...Object.entries(item.after).map(([field, after]) =>
                field in item.before
                  ? `- ${field}: ${JSON.stringify(item.before[field])} → ${JSON.stringify(after)}`
                  : `- ${field}: ${JSON.stringify(after)}`,
              ),
            ].join('\n'),
          ),
        ].join('\n\n'),
        'editor.cfg': JSON.stringify(draft, null, 2),
        'editor.css': Object.entries(draft)
          .map(([id, value]) => {
            const declarations = [
              value.size ? `font-size: ${value.size}px` : '',
              value.color ? `color: ${value.color}` : '',
              value.x !== undefined || value.y !== undefined
                ? 'position: relative'
                : '',
              value.x !== undefined ? `left: ${value.x}px` : '',
              value.y !== undefined ? `top: ${value.y}px` : '',
              value.width ? `width: ${value.width}px` : '',
              value.height ? `height: ${value.height}px` : '',
            ].filter(Boolean)
            return declarations.length
              ? `${cssSelectorFor(id)} { ${declarations.join('; ')}; }`
              : ''
          })
          .filter(Boolean)
          .join('\n'),
      }
      const baseManifest = {
        schema_version: 1,
        project_id: projectId,
        base_version_id: config.versionId,
        base_version_label: config.label,
        build_reference: config.buildReference,
        changes,
        files: [...Object.keys(coreFiles), 'manifest.json'],
      }
      const result = await submitEditorExport(
        projectId,
        config.versionId,
        changes,
        baseManifest,
      )
      const manifest = JSON.stringify(
        { ...baseManifest, content_sha256: result.contentSha256 },
        null,
        2,
      )
      const files = { ...coreFiles, 'manifest.json': manifest }
      await uploadEditorExportFiles(projectId, result.contentSha256, files)
      await finalizeEditorExport(result.exportId)
      setSentDraft(JSON.stringify(draft))
      setStampDismissed(false)
      setMessage(
        result.conflict
          ? 'Ajustes enviados para a Nó, com alerta de versão-base desatualizada; a Nó fará a conciliação.'
          : result.contentReplay
            ? 'Esses mesmos ajustes já tinham sido enviados; nada foi duplicado.'
            : 'Ajustes enviados para a Nó. Eles entram na próxima versão.',
      )
    } catch {
      setMessage(
        'Não foi possível concluir o envio. O rascunho foi preservado; tente novamente.',
      )
    } finally {
      setSending(false)
    }
  }

  const replaceImage = async (id: string, file: File) => {
    setImageError(null)
    if (!EDITOR_IMAGE_TYPES[file.type]) {
      setImageError({ id, text: 'Use uma imagem PNG, JPG, WebP ou GIF.' })
      return
    }
    if (file.size > EDITOR_IMAGE_MAX_BYTES) {
      setImageError({ id, text: 'A imagem passa de 5 MB. Escolha um arquivo menor.' })
      return
    }
    setUploading(true)
    try {
      change(id, 'logo', await uploadEditorImage(projectId, file))
    } catch {
      setImageError({ id, text: 'Não foi possível enviar a imagem. Tente de novo.' })
    } finally {
      setUploading(false)
    }
  }

  const sent = sentDraft !== null && sentDraft === JSON.stringify(draft)
  const screen = 'Página única'
  const component = selectedComponent
    ? componentFor(config, meta, selectedComponent)
    : null
  const controls = component ? controlsFor(component) : []
  const original = component ? meta[component.id]?.before : undefined
  const value = component
    ? {
        ...emptyValue,
        ...previewValues[component.id],
        ...Object.fromEntries(
          contentControls.flatMap((field) =>
            original?.[field] !== undefined ? [[field, original[field]]] : [],
          ),
        ),
        ...draft[component.id],
      }
    : emptyValue
  return (
    <section className="editor-workspace">
      <aside className="editor-screens">
        <p className="eyebrow">Página</p>
        <button type="button" className="selected" aria-current="page">
          {screen}
        </button>
        <div className="editor-base">
          <p className="eyebrow">Versão base</p>
          <h2>Editor · {config.label}</h2>
          <p>{config.buildReference}</p>
        </div>
      </aside>
      <div className="editor-canvas">
        <header>
          <span>Pré-visualização</span>
          <div className="editor-toolbar">
            <div className="device-toggle">
              <button
                aria-pressed={device === 'desktop'}
                onClick={() => setDevice('desktop')}
              >
                ▱ Desktop
              </button>
              <button
                aria-pressed={device === 'mobile'}
                onClick={() => setDevice('mobile')}
              >
                ▯ Celular
              </button>
            </div>
            <button
              type="button"
              className="editor-mode-toggle"
              aria-pressed={editorMode}
              onClick={() => setEditorMode((active) => !active)}
            >
              {editorMode ? '✓ Modo editor' : '✦ Modo editor'}
            </button>
            <button
              type="button"
              className="editor-mode-toggle editor-undo"
              onClick={undo}
              disabled={!history.length || sending}
              title="Desfazer a última alteração (Ctrl+Z)"
            >
              ↶ Desfazer
            </button>
          </div>
          <small>{target ? 'Preview controlado' : 'Ajustes locais'}</small>
        </header>
        <div
          className={`editor-preview ${device}${editorMode ? ' is-editing' : ''}`}
        >
          {target ? (
            <iframe
              key={previewRevision}
              ref={frameRef}
              title={`Preview controlado ${config.label}`}
              src={target.href}
              onLoad={sendPreview}
              sandbox="allow-forms allow-scripts allow-same-origin"
            />
          ) : (
            <div className="local-preview">
              <p className="eyebrow">{screen ?? 'Prévia'}</p>
              <p className="preview-disclaimer">
                A versão ainda não disponibiliza prévia integrada. Confira
                abaixo os ajustes do componente selecionado.
              </p>
              {component ? (
                <div
                  style={{ fontSize: `${value.size}px`, color: value.color }}
                >
                  {value.text || component.label || component.id}
                </div>
              ) : (
                <p>Nenhum componente liberado.</p>
              )}
              {value.logo ? (
                <p className="preview-disclaimer">Imagem: {value.logo}</p>
              ) : null}
            </div>
          )}
          {sent && !stampDismissed ? (
            <button
              type="button"
              className="editor-sent-stamp"
              onClick={() => setStampDismissed(true)}
              title="Fechar aviso"
            >
              <b>Enviado</b>
              <span>{nextVersionText(config.label)}</span>
            </button>
          ) : null}
        </div>
      </div>
      <aside className="editor-inspector">
        <p className="eyebrow">Elemento selecionado</p>
        {component ? (
          <div className="selected-component-card">
            <small title={component.screen ?? 'geral'}>{component.screen ?? 'geral'}</small>
            <strong>{component.label ?? component.id}</strong>
          </div>
        ) : (
          <div className="selection-empty">
            <span aria-hidden="true">{editorMode ? '↖' : '✦'}</span>
            <p>
              {editorMode
                ? 'Selecione um texto, botão ou imagem diretamente no preview.'
                : 'Ative o Modo editor para selecionar e ajustar um elemento no preview.'}
            </p>
          </div>
        )}
        {component ? (
          <fieldset className="component-controls" disabled={sending}>
            <legend>Ajustes</legend>
            {controls.includes('text') ? (
              <label>
                Texto
                <textarea
                  aria-label={`Texto ${component.id}`}
                  value={value.text}
                  rows={Math.min(8, Math.max(2, Math.ceil(value.text.length / 34) + (value.text.match(/\n/g)?.length ?? 0)))}
                  onChange={(event) =>
                    change(component.id, 'text', event.target.value)
                  }
                  placeholder="Digite seu ajuste"
                />
              </label>
            ) : null}
            {controls.includes('size') ? (
              <label>
                Tamanho <span>{value.size} px</span>
                <input
                  aria-label={`Tamanho ${component.id}`}
                  type="range"
                  min="8"
                  max="160"
                  value={value.size}
                  onChange={(event) =>
                    change(component.id, 'size', event.target.value)
                  }
                />
              </label>
            ) : null}
            {controls.includes('color') ? (
              <label>
                Cor
                <div className="color-options">
                  <input
                    aria-label={`Cor ${component.id}`}
                    type="color"
                    value={value.color}
                    onChange={(event) =>
                      change(component.id, 'color', event.target.value)
                    }
                  />
                  {['#141414', '#3D63DB', '#EDA33B', '#30A46C'].map((color) => (
                    <button
                      type="button"
                      key={color}
                      aria-label={`Usar cor ${color}`}
                      aria-pressed={value.color === color}
                      style={{ background: color }}
                      onClick={() => change(component.id, 'color', color)}
                    />
                  ))}
                </div>
              </label>
            ) : null}
            {controls.includes('logo') ? (
              <div className="image-control">
                <span>Imagem</span>
                {value.logo ? (
                  <img src={value.logo} alt="Imagem atual do elemento" />
                ) : null}
                <label className="image-upload-button">
                  {uploading ? 'Enviando imagem…' : 'Escolher imagem do computador'}
                  <input
                    type="file"
                    accept={Object.keys(EDITOR_IMAGE_TYPES).join(',')}
                    aria-label={`Imagem ${component.id}`}
                    disabled={uploading}
                    onChange={(event) => {
                      const file = event.target.files?.[0]
                      event.target.value = ''
                      if (file) void replaceImage(component.id, file)
                    }}
                  />
                </label>
                <small>PNG, JPG, WebP ou GIF, até 5 MB.</small>
                {imageError?.id === component.id ? (
                  <p role="alert">{imageError.text}</p>
                ) : null}
              </div>
            ) : null}
            <div className="layout-readout">
              <span>Posição</span>
              <strong>{value.x}, {value.y}</strong>
              <span>Tamanho</span>
              <strong>{value.width || 'auto'} × {value.height || 'auto'}</strong>
              <button
                type="button"
                onClick={() => {
                  change(component.id, 'x', '0')
                  change(component.id, 'y', '0')
                  change(component.id, 'width', '')
                  change(component.id, 'height', '')
                }}
              >
                Redefinir posição e tamanho
              </button>
            </div>
          </fieldset>
        ) : null}
        <p className="editor-help">
          No Modo editor, clique para selecionar, arraste para mover, use as
          alças para redimensionar e dê duplo clique em textos para editar.
          Para navegar pelo site (abrir menus, perguntas ou janelas), desligue
          o Modo editor. “Salvar” guarda o rascunho neste navegador; “Enviar
          para análise” manda os ajustes direto para a Nó.
        </p>
        <div className="editor-actions">
          <p className="eyebrow">
            {Object.keys(draft).length
              ? `${Object.keys(draft).length} componente(s) ajustado(s)`
              : 'Nenhum ajuste no rascunho'}
          </p>
          <button disabled={sending} className="button-outline" onClick={save}>
            Salvar ajustes
          </button>
          <button
            disabled={sending || sent || uploading}
            className="button-green"
            onClick={() => void send()}
          >
            {sending ? 'Enviando…' : sent ? '✓ Enviado' : 'Enviar para análise'}
          </button>
          {!confirmDiscard ? (
            <button
              disabled={sending}
              className="discard-button"
              onClick={() => setConfirmDiscard(true)}
            >
              Descartar rascunho
            </button>
          ) : (
            <>
              <button className="discard-button" onClick={discard}>
                Confirmar descarte
              </button>
              <button onClick={() => setConfirmDiscard(false)}>Cancelar</button>
            </>
          )}
          {message ? <p role="status">{message}</p> : null}
        </div>
      </aside>
    </section>
  )
}
