import { fireEvent, render, screen, waitFor } from '@testing-library/react'
import { BrowserRouter } from 'react-router-dom'
import { beforeEach, describe, expect, it, vi } from 'vitest'

const mocks = vi.hoisted(() => ({ listAdminScheduleItems: vi.fn(), getAdminScheduleSettings: vi.fn(), listAdminProjects: vi.fn(), saveKanbanItem: vi.fn(), setAdminDailyCapacity: vi.fn() }))
vi.mock('./admin-dashboard/admin-dashboard-service', () => ({ ...mocks, scheduleLoad: (items: Array<{ status: string; scheduled_date: string | null }>, from: string) => ({ [from]: items.filter((item) => item.status !== 'concluido' && item.scheduled_date === from).length }), wouldExceedDailyCapacity: (items: Array<{ id: string; status: string; scheduled_date: string | null }>, item: { id?: string; status?: string; scheduled_date?: string | null }, capacity: number) => !item.scheduled_date || item.status === 'concluido' ? false : items.filter((entry) => entry.id !== item.id && entry.status !== 'concluido' && entry.scheduled_date === item.scheduled_date).length + 1 > capacity, proposeThirtyDaySchedule: () => [{ title: 'V1 — entrega', macro_version: 'V1', status: 'a_fazer', scheduled_date: current, position: 5, beyondHorizon: false }] }))
import { SchedulePage } from './pages/SchedulePage'

const current = new Intl.DateTimeFormat('en-CA', { timeZone: 'America/Sao_Paulo', year: 'numeric', month: '2-digit', day: '2-digit' }).format(new Date())
const item = (id: string) => ({ id, project_id: 'project-1', project_name: 'Projeto Alfa', title: `Item ${id}`, phase: null, macro_version: 'V1', status: 'a_fazer', scheduled_date: current, completed_at: null, position: 0 })

describe('F3-12 cronograma', () => {
  beforeEach(() => { vi.clearAllMocks(); mocks.listAdminScheduleItems.mockResolvedValue([item('1'), item('2'), item('3'), item('4'), item('5')]); mocks.getAdminScheduleSettings.mockResolvedValue({ dailyItemCapacity: 5 }); mocks.listAdminProjects.mockResolvedValue([{ id: 'project-1', name: 'Projeto Alfa', projectStatus: 'CONVERTIDO' }]); mocks.saveKanbanItem.mockResolvedValue(item('saved')); mocks.setAdminDailyCapacity.mockResolvedValue({ dailyItemCapacity: 4 }) })
  it('C1/C5 mostra quadro e carga diária', async () => { render(<BrowserRouter><SchedulePage /></BrowserRouter>); expect(await screen.findByText('Item 1')).toBeVisible(); expect(screen.getByText('5/5')).toBeVisible() })
  it('C4 filtra projeto e macroversão', async () => { render(<BrowserRouter><SchedulePage /></BrowserRouter>); await screen.findByText('Item 1'); fireEvent.change(screen.getByLabelText('Filtrar por macroversão'), { target: { value: 'V2' } }); expect(screen.getByText(/Nenhum item corresponde/)).toBeVisible() })
  it('C6 pede confirmação antes de criar além da capacidade', async () => { render(<BrowserRouter><SchedulePage /></BrowserRouter>); await screen.findByText('Item 1'); fireEvent.change(screen.getByLabelText('Projeto do novo item'), { target: { value: 'project-1' } }); fireEvent.change(screen.getByLabelText('Título do novo item'), { target: { value: 'Sexto item' } }); fireEvent.click(screen.getByRole('button', { name: 'Criar item' })); expect(screen.getByText(/Conflito de capacidade/)).toBeVisible(); expect(mocks.saveKanbanItem).not.toHaveBeenCalled(); fireEvent.click(screen.getByRole('button', { name: 'Confirmar conflito' })); await waitFor(() => expect(mocks.saveKanbanItem).toHaveBeenCalled()) })
  it('C7 só grava a proposta de 30 dias após confirmação', async () => { render(<BrowserRouter><SchedulePage /></BrowserRouter>); await screen.findByText('Item 1'); fireEvent.change(screen.getByLabelText('Projeto convertido'), { target: { value: 'project-1' } }); await waitFor(() => expect(screen.getByLabelText('Projeto convertido')).toHaveValue('project-1')); fireEvent.click(screen.getByRole('button', { name: 'Gerar proposta' })); expect(await screen.findByRole('button', { name: 'Confirmar proposta' })).toBeVisible(); expect(mocks.saveKanbanItem).not.toHaveBeenCalled(); fireEvent.click(screen.getByRole('button', { name: 'Confirmar proposta' })); await waitFor(() => expect(mocks.saveKanbanItem).toHaveBeenCalledWith('project-1', expect.objectContaining({ title: 'V1 — entrega' }))) })
})
